# Test case for gpt-1.3b
apiVersion: cpod.sxwl.ai/v1beta1
kind: CPodJob
metadata:
  labels:
    app.kubernetes.io/name: cpodjob
    app.kubernetes.io/instance: cpodjob-sample
    app.kubernetes.io/part-of: cpodjob
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cpodjob
  name: cpodjob-sample
  namespace: cpodoperator
spec:
  image: registry.cn-beijing.aliyuncs.com/sxwl-ai/modelscope_gpt3_1h1g1dp:latest
  command:
    - torchrun
    - --nproc_per_node=8
    - finetune_poetry.py
  jobType: pytorch
  gpuRequiredPerReplica: 8
  gpuType: NVIDIA-GeForce-RTX-3090
  workerReplicas: 1
  pretrainModelName: chatglm3-6b
  pretrainModelPath: /sixpen_models/chatlm3
  datasetName: modihand-dataset
  datasetPath: /workspace/chinese-poetry-collection
  

  
